### PR TITLE
Add support for 3rd party framework (currently Quasar Framework)

### PR DESCRIPTION
**Pull request by tomers**
* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR adds support for integration with a framework. Currently the Quasar Framework is (partly) supported. 
The PR adds ability to specify framework specific components to VFG. Currently _fieldCheckbox_ and _fieldInput_ [were added](https://github.com/tomers/vue-form-generator/tree/master/src/fields/frameworks/quassar).

- **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
Please read [README.md](https://github.com/tomers/vue-form-generator#framework-support) for further info.
- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:
You are invited to join development discussions @ Quasar Framework [Discord channel](https://chat.quasar-framework.org/)

### CODE REVIEW

**Comment by zoul0813** [comment]
Not quite sure what benefit this provides? Can support for Quaser not be added as as a third party addon to VFG without being embedded directly into VFG?

**Comment by zoul0813** [comment]
Or perhaps as a quaser specific fork of VFG...?

**Comment by tomers** [comment]
There is no need at all to embedd Quasar Framework in VFG!

The QF components will not be used at all by non Quasar users. No
additional dependencies in package.json were added.

This PR adds native Quasar look to VFG forms, as it uses the framework's
components. See:

https://cdn.discordapp.com/attachments/450984042284711936/452900808174993418/Screen_Shot_2018-06-03_at_20.25.40.png

**Comment by zoul0813** [comment]
@tomers it does so by adding new components to VFG though, rather than as a third-party addon.

To add support for 2 components ... 50 files were added/changed.  I understand most of these are in the `dev` folder ... but that seems a bit much.

VFG V3's current development plan is to stream line VFG core, and separate out the "optional" components into separate "vfg-field-*" packages that are truly optional and can be added one-by-one (at the moment, it's all or none).

In addition, you modified formGenerator.vue to support the new frameworks ... not quite sure I understand the need for this?

To me, it seems like this type of feature would be better handled as either a framework specific fork, or third-party VFG field components.

If you have any ideas or thoughts on how we could implement a "plugin architecture" for VFG V3 that would allow for something like this to be a third-party "plugin" or "module" ... that would be great.

**Comment by zoul0813** [comment]
I'm closing this PR - feel free to open an issue to discuss possible plugin architecture in v3.

If you create a quaser specific fork of VFG, let us know and we can link to it in the README as well.

**Pull request closed without merging**
