### PR TITLE
adding bootstrap class support

### PR DESCRIPTION
**Pull request by averagejoe77**
Modified the scss in the formGroup.vue file to target elements that do not have a class that starts with 'col-' and set their width to 100%. Removed 'width:100%' from the form-group selector.

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by lionel-bijaoui** [comment]
Hello @averagejoe77 , thank you for your PR !

**Comment by averagejoe77** [comment]
> Hello @averagejoe77 , thank you for your PR !

I am sorry I thought you guys would have tested and run the build before this got merged. I only updated the .vue file but did not run the build.

The latest branch (2.3.0) with this PR merged in does not contain the actual change in the css file.

Do you want me to create a new PR with the actual css files getting updated?

**Comment by zoul0813** [comment]
@averagejoe77 Travis CI should have handled that - looks like something went wrong.

@lionel-bijaoui have any thoughts?

**Comment by lionel-bijaoui** [comment]
@zoul0813 See https://github.com/vue-generators/vue-form-generator/issues/472#issuecomment-425822612

**Comment by zoul0813** [comment]
Yep - I’ll correct that with 2.3.1, sorry about that.

**Pull request merged**
