### PR TITLE
Node 10 Compatibility + Added vue-multiselect noResult slot option

### LINKED ISSUE #380: Set slot with VueMultiSelect
I'm using vueMultiSelect and there's an entry for `slot` to set the label for `not found`, but I can't set this through `vue-form-generator`. Does anyone knows how to set this?

### LINKED ISSUE #457: Installation is broken due to broken nan package
*** This issue has a workaround. Please read below. ***

Cloning the repository and running `npm install` fails:
```
$ npm install

...

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:In file included from 6:
../fsevents.ccIn file included from :../../nan/nan.h6::
192In file included from :
../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112../../nan/nan_maybe_43_inl.h::15112:: 15: error: error: no nomember  membernamed  named'ForceSet'  'ForceSet'in  in'v8::Object' 'v8::Object'

...

make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.2.1/bin/node" "/Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-sass
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

The issue is similar to the issue found in other projects, e.g. https://github.com/justadudewhohacks/opencv4nodejs/issues/295

# RESOLUTION
This is a temporary resolution, until a newer release of the `nan` package is made.
Replace `nan` package with the HEAD of the Github repo:
```
$ git diff package.json 
diff --git a/package.json b/package.json
index c9335fa..4a98b47 100644
--- a/package.json
+++ b/package.json
@@ -85,6 +85,7 @@
     "mocha": "2.5.3",
     "mocha-generators": "1.2.0",
     "mocha-loader": "0.7.1",
+    "nan": "git+https://github.com/nodejs/nan.git",
     "node-sass": "4.7.2",
     "phantomjs-prebuilt": "2.1.14",
     "pug": "2.0.0-beta11",
```

### PR DESCRIPTION
**Pull request by qkdreyer**
* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

Fixes #457
Fixes #380

### CODE REVIEW

**Comment by zoul0813** [comment]
@lionel-bijaoui as you're actively working on merging a PR, can you review this real quick to make sure we won't have any conflicts ... don't want to make your life any more complicated than it needs to be.

**Comment by qkdreyer** [comment]
It shouldn't be hard to resolve any conflitcs since it's only one package version modification and 2 lines added :)

**Comment by qkdreyer** [comment]
Do you know when will be it released ?

**Comment by lionel-bijaoui** [comment]
@qkdreyer I don't know, I hope soon

**Comment by zoul0813** [comment]
@lionel-bijaoui I can release it now, if you think that's OK? I think the dep and dev tool work you did is enough to call this a "v2.3.0 release" ... ?

**Comment by lionel-bijaoui** [comment]
Right now my problem is that Travis fail, but locally all the test are green. I don't understand...

**Comment by zoul0813** [comment]
I just grabbed the latest code, and ran the tests ... I get a bunch of errors output, but the test suite says they ran successfully.  Want me to open a new issue so we can track problems with releasing v2.3.0?

**Comment by lionel-bijaoui** [comment]
I get weird outputs, but nothing like what Travis has.
Yes please 👍

**Pull request merged**
