### PR TITLE
Fix NaN with value 0 on input type number/range.

### PR DESCRIPTION
**Pull request by andrelec1**
* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Add simple *1 on value for forcing number type.

- **What is the current behavior?** (You can also link to an open issue here)
https://github.com/vue-generators/vue-form-generator/issues/425

* **What is the new behavior (if this is a feature change)?**
Bug fix

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by zoul0813** [comment]
I don't agree with these changes - but am open to being convinced otherwise as I may be missing something here.

NaN is the appropriate value to be used when the user enters anything that is "not a number".  I also don't agree that numbers stored as strings '0', '1', '2', etc ... should be treated as anything other than strings.  The field expects a number, `parseInt('0')` or `new Number('5')` should be used to convert string values into their number representation before passing the model to VFG.

**Comment by andrelec1** [comment]
I found the real issue, and change my commit ...

**Comment by zoul0813** [comment]
What’s wrong with the NaN result? Is the browser having an issue displaying NaN in the input?

**Comment by andrelec1** [comment]
in fact, if you put 0 if the field, you didn't convert the value in number  ... ( if (0)  => false )

```onInput($event) {
			let value = $event.target.value;
			switch(this.schema.inputType.toLowerCase()) {
				case "number":
				case "range":
					if($event.target.valueAsNumber) {
						value = $event.target.valueAsNumber;
					}
					break;
			}
			this.value = value;
		},
```
So when value go throut `formatNumberToModel` ( my first wrong fix :/ ) you have a string ... so you put NaN in model ...
In some case you realy want put 0 in field and get 0 in model ... 0 is valide number ... 

https://jsfiddle.net/0mg1v81e/1978/

**Comment by qkdreyer** [comment]
I can confirm this fixes #425.
You can check it here : https://jsfiddle.net/0mg1v81e/2323/

**Comment by zoul0813** [comment]
Not sure I understand what's being fixed here.

Here's the same JSFiddle, pointing to the official 2.1.1 version of VFG ... same result, unless I'm missing something?

I'm able to type in -10, -25, 0, etc ... and the form validates them all, what am I missing here?

**Comment by qkdreyer** [comment]
Without PR : http://recordit.co/bjcamzQq62
With PR : http://recordit.co/XvuAQjTNBV

**Comment by zoul0813** [comment]
Do you get the same result when using my fiddle against 2.1.1?

**Comment by qkdreyer** [comment]
I'm sorry but I am not able to find your fiddle...

**Comment by zoul0813** [comment]
Doh, I didn't link it ... https://jsfiddle.net/94dcctbf/3/

**Comment by qkdreyer** [comment]
Could you hotfix/merge this ASAP since it’s a BC minor change and some of us rely on this library in production ?

**Pull request merged**
