### PR TITLE
Update README.md : Added reference to how to do manual validation of the form.

### PR DESCRIPTION
**Pull request by enyosolutions**
* **Please check if the PR fulfills these requirements**

- [X ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs update
- **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no breaking changes

* **Other information**:

### CODE REVIEW

**Comment by zoul0813** [comment]
This example isn’t accurate.  async validation returns a promise, and v3 will be moving toward this as a standard...

**Comment by enyosolutions** [comment]
This example is accurate for the current version, it's probably best to add the two versions ?

**Comment by zoul0813** [comment]
V2 supports async validation, when enabled in form options

**Comment by enyosolutions** [comment]
@zoul0813 sorry to ask but which form options. 
Both the readme and the gitbook references only 3 options 


Property | Type | Description
-- | -- | --
validateAfterLoad | boolean | Execute validation after model loaded
validateAfterChanged | boolean | Execute validation after every change
fieldIdPrefix | string | Prefix to add to every field's id. Will be prepended to ids explicity set in the schema, as well as auto-generated ones.

**Comment by zoul0813** [comment]
@enyosolutions the documentation is a bit behind, validateAsync was [added quite a while ago](https://github.com/vue-generators/vue-form-generator/commit/5a26ef1b4f4aaccd0c84137cd1edd7ecb0c8bce1) to support proper Async Validation.

It's also going to be the way V3 functions by default.

I'm closing this issue for now, as I don't think that manual validation samples should be in the README, and instead, should be updated in Gitbooks.

@lionel-bijaoui do we have access to the Gitbook Docs to update them? If not, should we switch over to something new so we can start properly updating the docs?

**Pull request closed without merging**
