### PR TITLE
Add form field align.

### PR DESCRIPTION
**Pull request by Wesamgerges**
* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

- **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by DelfsEngineering** [comment]
Could this not be better handled already  With `fieldStyleClasses` ?

**Comment by Wesamgerges** [comment]
This is mainly for fields that require the text to me on its right like checkbox or radio.
I have tried to use css, however, I couldn't get it right.
You may have more experience in css than me.
If you have a better solution, please let me know :) 
Thanks

**Comment by DelfsEngineering** [comment]
`labelClasses` and  `fieldClasses` classes are available. Perhaps they need to be implemented better or additional hooks for clases to be added?

**Comment by zoul0813** [comment]
As @DelfsEngineering stated, you should use CSS for this.

If you find there is t enough support with the existing fieldClasses and labelClasses, please provide a JSFiddle example of your use case so we can take a look.

**Comment by Wesamgerges** [comment]
iagree

I just need to do this.
I don't know if this can be done with just css.

**Comment by zoul0813** [comment]
Use the required attribute and :after pseudo class?

**Pull request closed without merging**
